apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: elasticsearch
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: elasticsearch
    spec:
      containers:
        - env:
            - name: bootstrap.memory_lock
              value: "false"
            - name: cluster.initial_master_nodes
              value: estrudesk01
            - name: discovery.seed_hosts
              value: estrudesk01
            - name: node.name
              value: estrudesk01
            - name: xpack.security.enabled
              value: "false"
            - name: xpack.security.http.ssl.enabled
              value: "false"
          image: elasticsearch:8.0.0
          name: elasticsearch
          ports:
            - containerPort: 9200
            - containerPort: 9300
          resources: 
              limits:
                memory: "1073741824"
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elasticsearch
      restartPolicy: Always
      volumes:
        - name: elasticsearch
          persistentVolumeClaim:
            claimName: elasticsearch
status: {}
