apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: trudesk
  name: trudesk
spec:
  ports:
    - name: "8118"
      port: 8118
      targetPort: 8118
  selector:
    io.kompose.service: trudesk
status:
  loadBalancer: {}
